def getEmergencyArray():
    sentences = [
        "He's not waking up, no matter what I do!",
        "She fell down the stairs and isn't moving.",
        "He's clutching his chest and can't breathe properly.",
        "She's having a seizure and I don't know what to do!",
        "He suddenly can't move the left side of his body.",
        "Her fever is dangerously high and won't come down.",
        "He's become violent and I'm afraid he'll hurt himself or me.",
        "She wandered off and I can't find her anywhere.",
        "I think he swallowed some cleaning products!",
        "She's been vomiting non-stop for hours.",
        "There's blood in his urine and he's in pain.",
        "She suddenly can't see anything.",
        "He's complaining of the worst headache of his life.",
        "He's seeing things that aren't there and is terrified.",
        "She's talking about ending her life.",
        "He fainted and I can't get him to come around.",
        "She's having what looks like an allergic reaction.",
        "His skin and eyes have turned yellow.",
        "She has a severe rash all over her body.",
        "He's coughing up blood.",
        "She's shaking uncontrollably and feels very cold.",
        "I think he might have broken his hip in a fall.",
        "She has a large, unexplained bruise on her head.",
        "He's bleeding heavily and I can't get it to stop.",
        "She's so dizzy she can't stand up.",
        "He suddenly can't speak or understand what I'm saying.",
        "She's complaining of severe stomach pain.",
        "He's having trouble breathing and his lips are turning blue.",
        "I think she might have had a stroke.",
        "He's showing signs of a heart attack.",
        "She has severe burns from spilling hot water.",
        "He's not making any sense and seems completely disoriented.",
        "She's having a severe asthma attack and her inhaler isn't helping.",
        "I think he might have overdosed on his medication.",
        "She's having a severe panic attack and can't calm down.",
        "He's become completely unresponsive to any stimuli.",
        "She's having hallucinations and is very agitated.",
        "He's showing signs of severe dehydration.",
        "He's having severe withdrawal symptoms.",
        "She's fallen and hit her head hard on the floor.",
        "He's having difficulty swallowing and is drooling excessively.",
        "I think she might have had an aneurysm.",
        "He's showing signs of a diabetic emergency.",
        "He's become combative and I can't control him.",
        "He's having severe tremors that won't stop.",
        "He's showing signs of internal bleeding.",
        "He's having severe chest pains that radiate to his arm.",
        "She's become completely catatonic.",
        "She's having severe mood swings and talking about harming herself.",
        "He's showing signs of liver failure.",
        "I think she might have had a pulmonary embolism.",
        "He's having a severe allergic reaction to a new medication.",
        "She's become extremely lethargic and won't respond to me.",
        "I think he might have appendicitis.",
        "She's having severe vertigo and can't stop vomiting.",
        "He's showing signs of a severe urinary tract infection.",
        "He's having severe dental pain and his face is swollen.",
        "She's had a sudden loss of hearing in both ears.",
        "She's showing signs of severe malnutrition.",
        "He's having difficulty breathing and his chest feels tight.",
        "I think she might have had a transient ischemic attack.",
        "She's having severe muscle spasms and cramping.",
        "He's become extremely agitated and is pacing non-stop.",
        "She's having severe night terrors and won't sleep.",
        "She's showing signs of severe anxiety and can't be calmed down.",
        "He's having difficulty with basic tasks he could do yesterday.",
        "I think she might have a brain tumor.",
        "He is attacking me!",
        "Im bleeding so much",
        "Ahh, Help!",
        "I smell smoke! Is that a fire!",
        "Ah, its burning!",
        "Stop hitting her please!",
        "Ah he is overdosing",
        "Im losing consciousness",
        "Dont drink that! Thats Bleach!",
    "help I cant breathe", 
    "my chest hurts really bad",
    "hes not responding",
    "shes having a seizure", 
    "theres blood everywhere", 
    "the patient is unconscious",
    "his heart stopped beating", 
    "she collapsed on the floor",
    "hes choking and cant speak", 
    "the patient is turning blue",
    "I think Im having a heart attack",
    "theres severe bleeding that wont stop", 
    "she suddenly cant move her left side", 
    "hes having difficulty speaking and seems confused", 
    "the patient fell and hit their head hard",
    "I cant feel my legs anymore", 
    "shes having an allergic reaction and her throat is closing",
    "he suddenly lost consciousness",
    "the patient is not breathing", 
    "theres severe burns all over", 
    "she cant stop convulsing",
    "his blood pressure is dangerously high",
    "the patient is showing signs of a stroke", 
    "theres severe trauma to the head", 
    "I think she overdosed",
    "hes having severe chest pains radiating to his arm",
    "the patient is unresponsive to stimuli",
    "theres a deep wound with arterial bleeding", 
    "she cant breathe and is gasping for air",
    "his pulse is extremely weak",
    "the patient is having severe difficulty breathing", 
    "theres signs of internal bleeding", 
    "she suddenly became paralyzed",
    "hes having a severe asthma attack and the inhaler isnt working", 
    "the patient is showing signs of shock",
    "theres a suspected spinal injury", 
    "she has severe abdominal pain and is vomiting blood",
    "his temperature is dangerously high",
    "the patient is having a severe allergic reaction",
    "theres a possible drug interaction causing severe symptoms"
    "she is experiencing severe pregnancy complications",
    "hes having diabetic shock",
    "the patient has severe burns from chemicals",
    "theres a suspected heart attack in progress",
    "she is having difficulty breathing and chest pain",
    "hes showing signs of a severe infection",
    "the patient has lost a lot of blood",
    "theres a severe head injury with loss of consciousness", 
    "she is having severe difficulty swallowing and breathing",
    "hes having a severe mental health crisis and is dangerous",
    "theres an active shooter in the hospital", 
    "someone jumped from the roof", 
    "the elevator is stuck and theres a woman in labor inside", 
    "the oxygen supply system has failed", 
    "theres a chemical spill in the lab", 
    "the patient is threatening staff with a weapon", 
    "someone released pepper spray in the ward", 
    "theres a fire in the pharmacy", 
    "the psychiatric patient has taken a hostage", 
    "the defibrillator isnt working and we need it now",
    "the backup generator failed and we have patients on ventilators",
    "someone stole a newborn from the nursery", 
    "theres a bomb threat in the building",
    "the patient is having an adverse reaction to anesthesia",
    "the MRI machine is smoking and making strange noises",
    "theres a gas leak in the cafeteria", 
    "multiple patients are having allergic reactions to the food", 
    "someone contaminated the water supply", 
    "the patient is trapped in the bathroom and unresponsive",
    "theres a violent family member attacking staff",
    "the radiation therapy machine is malfunctioning", 
    "someone fell into the biohazard disposal bin",
    "the patient got their hand stuck in medical equipment", 
    "theres a structural collapse in the east wing", 
    "multiple staff members suddenly fell ill",
    "the patient is stuck in the CT scanner", 
    "theres an electrical fire in the operating room",
    "someone released the emergency locks and secured doors",
    "the cooling system failed in the blood bank", 
    "theres a toxic gas leak in the laboratory",
    "multiple IV pumps are giving wrong doses",
    "the patient is having a severe reaction to contrast dye",
    "theres a flood in the basement affecting critical equipment",
    "someone tampered with the medication supply",
    "the patient is trapped under fallen equipment", 
    "theres a power surge affecting life support systems", 
    "multiple alarm systems are failing simultaneously",
    "the patient is bleeding into their artificial joint",
    "theres a breach in the isolation ward",
    "someone collapsed in the parking structure", 
    "the patient is having complications during dialysis",
    "someone broke the glass in the psychiatric unit", 
    "theres a severe weather emergency affecting hospital access", 
    "the patient is stuck in restraints during a fire",
    "multiple staff members are down from toxic fumes",
    "theres an unauthorized person in the restricted area",
    "hey mom your lips look kind of blue are you cold", 
    "nurse I noticed dad hasnt moved at all since I got here", 
    "the machine keeps beeping but nobody has come to check", 
    "I think the IV line might have come out theres blood on the sheets",
    "she keeps saying her arm feels funny and shes slurring her words", 
    "the bandage is completely soaked through already", 
    "I noticed the numbers on his monitor keep getting lower"
    "hey nurse she hasnt blinked or moved for the past 10 minutes", 
    "mom your face is drooping on one side when you smile", 
    "doctor his fingertips and toes are turning really dark", 
    "the bandage is completely red and blood is dripping on the floor", 
    "nurse she keeps saying she cant feel her legs anymore",
    "hey the machine says his oxygen is at 82", 
    "his heart rate monitor keeps showing zero then coming back", 
    "she says her chest feels like an elephant is sitting on it",
    "doctor his skin is turning yellow and hes really confused",
    "the IV site is really swollen and her arm feels hot",
    "nurse she hasnt urinated in over 24 hours", 
    "his blood pressure reading is 220 over 110", 
    "doctor his temperature is 104 and the medicine isnt helping",
    "nurse the surgical site is black around the edges", 
    "hey his breathing sounds like a whistle when he exhales", 
    "she cant squeeze my hand anymore on her right side", 
    "doctor he keeps saying he sees bugs crawling everywhere", 
    "the dialysis machine keeps showing error messages",
    "nurse her stomach is getting really hard and distended", 
    "his skin is cold and clammy and hes not responding", 
    "she keeps saying everything is spinning and now cant talk", 
    "doctor the chest tube stopped draining but hes struggling to breathe",
    "hey his legs are completely different colors",
    "the heart monitor shows his rate is over 180",
    "doctor his insulin pump is beeping and he wont wake up",
    "nurse theres coffee ground stuff in his vomit",
    "honey your lips are turning blue while youre sleeping",
    "mom keeps staring at the wall and wont respond to her name", 
    "grandpa hasnt moved from that position all day", 
    "theres black stuff in his throw up on the pillow",
    "she cant lift her arms anymore since this morning", 
    "dad keeps saying he cant feel the left side of his face", 
    "her eyes are rolling back and shes shaking all over", 
    "hes sweating so much the bed is soaked through",
    "his skin is turning yellow and his stomach is huge", 
    "she hasnt been able to keep water down for two days",
    "dad cant catch his breath even sitting still", 
    "theres blood in his urine and hes doubled over", 
    "she keeps grabbing her head and crying in pain", 
    "his legs are swollen three times their normal size",
    "mom cant form any words just making sounds", 
    "grandpa fell and now his hip looks completely wrong",
    "shes been unconscious since taking those pills",
    "his chest pain is spreading to his jaw now",
    "she keeps saying she sees people who arent here",
    "dad hasnt eaten or drunk anything in three days",
    "theres blood soaking through his bandages", 
    "grandma fell and hit her head and keeps vomiting", 
    "hes talking nonsense and really aggressive", 
    "her face is super swollen after eating peanuts",
    "mom cant move her legs to get out of bed", 
    "his skin is gray and hes barely breathing", 
    "shes having trouble staying awake after the fall",
    "dad keeps forgetting what year it is", 
    "theres a weird bulge in his stomach that wasnt there before",
    "she hasnt moved from the bathroom in hours",
    "his fever is 104 and tylenol isnt helping",
    "mom keeps losing consciousness when she stands",
    "grandpa is having chest pain down both arms", 
    "her breathing sounds like shes underwater",
    "hes seeing double and cant walk straight", 
    "she hasnt used the bathroom in three days", 
    "dad keeps grabbing his chest and cant talk", 
    "theres blood coming from his ears after the fall",
    "her skin is covered in purple spots suddenly", 
    "he cant remember any of our names anymore",
    "mom is having trouble breathing and her inhaler isnt working",
    "grandma keeps falling when she tries to walk", 
    "his face is drooping on one side when he talks",
    "she hasnt woken up and its been 12 hours",
    "dad is confused about where he is and fighting us",
    "theres blood in his stool and hes really pale", 
    "her heart is racing and she cant calm down", 
    "he keeps saying his throat is closing up", 
    "mom cant move her fingers anymore", 
    "grandpa is having severe tremors that wont stop", 
    "shes complaining that her vision is all black", 
    "his skin is really cold but hes burning up", 
    "she cant swallow and is drooling everywhere",
    "dad is having trouble speaking clearly",
    "theres a large purple bruise spreading on his stomach",
    "her legs are completely different temperatures",
    "he hasnt responded to any noise or touch",
    "mom keeps saying her head feels like its exploding", 
    "grandma cant feel anything below her waist", 
    "his breathing is really shallow and fast",
    "she keeps losing balance and falling over", 
    "dad is having severe pain in his lower back",
    "theres swelling around his surgical site", 
    "her arms and legs are completely rigid",
    "he keeps passing out when he tries to stand",
    "mom is having severe pain in her left arm", 
    "grandpa hasnt taken a breath in 30 seconds", 
    "shes having trouble keeping her eyes open", 
    "his skin is turning blue around his lips", 
    "she cant remember what happened today", 
    "dad is having severe stomach pain and fever",
    "theres blood in her vomit on the floor",
    "he keeps saying he cant feel his feet", 
    "mom is having trouble focusing her eyes",
    "grandma is having severe chest pressure", 
    "his wound is hot and red and spreading",
    "she cant move her tongue properly",
    "dad is having trouble staying conscious", 
    "theres a weird smell coming from his wound",
    "her pulse is really weak and thread", 
    "he keeps saying everything is spinning",
    "mom cant lift her head off the pillow", 
    "grandpa is having trouble breathing lying down",
    "shes become really confused about simple things",
    "his skin is turning gray and mottled", 
    "she cant remember her own birthday", 
    "dad is having severe pain in his neck", 
    "theres blood coming from his nose wont stop", 
    "her face is swelling up on one side",
    "he keeps saying he feels like hes dying", 
    "mom is having severe abdominal pain",
    "grandma keeps grabbing at her chest",
    "his speech is completely slurred now",
    "she cant feel her fingers anymore",
    "dad is having trouble staying awake",
    "theres a large bump forming on his head",
    "her breathing sounds like snoring but shes awake",
    "he keeps saying he cant see anything",
    "mom is having severe back pain", 
    "his catheter is completely blocked and hes in pain", 
    "she keeps pulling out her IV lines", 
    "theres blood pooling under the bed",
    "he hasnt moved from that position for hours",
    "his feeding tube came out completely",
    "she keeps hitting her head against the wall",
    "theres smoke coming from the electrical outlet",
    "he just swallowed a handful of pills",
    "shes turning purple and gasping", 
    "his trach tube fell out",
    "theres glass everywhere and hes barefoot", 
    "he drank the hand sanitizer",
    "shes having trouble with her dialysis port", 
    "his colostomy bag burst", 
    "she ate something from the sharps container", 
    "theres a fire in the laundry room",
    "he keeps pulling at his chest tubes", 
    "shes trying to walk with a broken hip",
    "his wound vac isnt working",
    "she just had a grand mal seizure", 
    "theres water leaking onto the electrical equipment", 
    "he keeps removing his restraints", 
    "his central line is bleeding", 
    "she swallowed her dentures", 
    "shes having an adverse reaction to the blood transfusion", 
    "his ventilator just stopped working",
    "theres a strange odor coming from his wound", 
    "he just stabbed himself with a fork", 
    "shes having severe chest pain after her surgery", 
    "his port is infected and red",
    "she drank the bath soap", 
    "theres blood in his CPAP mask", 
    "he keeps trying to remove his staples", 
    "shes becoming combative with staff",
    "his glucose is reading high", 
    "she hasnt had a bowel movement in a week", 
    "theres pus coming from his surgical site", 
    "he keeps trying to eat non food items", 
    "shes having trouble with her pacemaker",
    "his skin is breaking down rapidly",
    "she just fell in the shower",
    "theres a chemical spill in his room", 
    "he keeps scratching his surgical site", 
    "shes having severe pain in her stoma",
    "his oxygen levels keep dropping",
    "she just had a stroke I think", 
    "theres blood in his urine bag", 
    "he keeps pulling out his nasogastric tube", 
    "shes becoming extremely aggressive", 
    "his foot is turning black", 
    "she keeps trying to leave the unit", 
    "theres a power outage and his ventilator battery is low",
    "he just had a massive heart attack",
    "shes having trouble with her insulin pump",
    "his fistula is bleeding heavily",
    "she keeps trying to drink bleach",
    "theres a code black in progress",
    "he just became unresponsive",
    "shes having severe withdrawal symptoms",
    "his chest tube is kinked",
    "she keeps trying to hurt herself",
    "theres a violent patient in the hallway",
    "he just had a severe allergic reaction",
    "shes bleeding from her surgical drain", 
    "his tracheostomy is blocked",
    "she keeps having panic attacks",
    "theres a fire in the kitchen",
    "he just collapsed in the bathroom",
    "shes having trouble with her breathing tube",
    "his feeding pump is malfunctioning",
    "she keeps trying to pull out her catheter",
    "theres a code gray in progress",
    "he just had a severe asthma attack",
    "shes having complications from her medication",
    "his wound is dehiscing",
    "she keeps trying to remove her stitches",
    "theres a security breach on the floor",
    "he just had a seizure and isnt waking up",
    "shes having severe pain in her chest",
    "his blood pressure is critically low",
    "she keeps trying to jump out of bed",
    "theres a code red in progress",
    "he just became extremely confused",
    "shes having trouble with her breathing",
    "his infection is spreading rapidly",
    "she keeps trying to harm staff",
    "theres a hazardous material spill",
    "he just had a severe panic attack",
    "shes having trouble with her heart rhythm",
    "his oxygen tank is empty",
    "she keeps trying to remove her bandages",
    "theres an active shooter in the building",
    "he just became extremely agitated",
    "shes having severe abdominal pain",
    "his feeding tube is blocked",
    "she keeps trying to swallow inedible objects",
    "theres a code silver in progress",
    "he just had a severe reaction to medication",
    "shes having trouble with her blood pressure",
    "his wound is severely infected",
    "she keeps trying to leave her room",
    "theres a bomb threat in the facility",
    "he just became extremely violent",
    "shes having trouble with her breathing treatments",
    "his central line is infected",
    "she keeps trying to remove her IV",
    "theres a code orange in progress",
    "he just had a severe allergic reaction",
    "shes having trouble with her oxygen levels",
    "his surgical site is opening up",
    "she keeps trying to harm herself",
    "theres a violent family member present",
    "he just became extremely disoriented",
    "shes having trouble with her medication",
    "his breathing tube is displaced",
    "she keeps trying to climb over the rails",
    "theres a code purple in progress",
    "he just had a severe anxiety attack",
    "shes having trouble with her heart",
    "his infection is not responding to antibiotics",
    "she keeps trying to remove her dressings",
    "theres an unauthorized person on the unit",
    "he just became extremely paranoid",
    "shes having trouble with her blood sugar",
    "his wound is bleeding heavily",
    "she keeps trying to pull out tubes",
    "theres a code yellow in progress", 
    "he just had a severe reaction to contrast",
    "shes having trouble with her kidneys", 
    "his chest tube is leaking",
    "she keeps trying to get out of restraints",
    "theres a hostile visitor in the room",
    "he just became extremely aggressive", 
    "shes having trouble with her liver", 
    "his feeding tube is leaking",
    "she keeps trying to remove monitoring equipment", 
    "he just had a severe reaction to anesthesia",
    "shes having trouble with her blood pressure cuff", 
    "his surgical site is infected", 
    "she keeps trying to disconnect equipment",
    "he just became extremely combative", 
    "shes having trouble with her oxygen mask", 
    "his catheter is infected",
    "she keeps trying to remove her trach", 
    "he just had a severe reaction to transfusion",
    "shes having trouble with her ventilator",
    "his wound vac is leaking", 
    "he just became extremely hostile",
    "shes having trouble with her dialysis",
    "his staples are coming out",
    "she keeps trying to remove her pacemaker leads",
    "he just had a severe reaction to dye", 
    "shes having trouble with her oxygen supply",
    "his chest tube is dislodged",
    "she keeps trying to remove her monitoring leads", 
    "he just became extremely violent", 
    "shes having trouble with her breathing machine",
    "she keeps trying to remove her IV line",
    "shes having trouble with her breathing treatment",
    "he just had a severe reaction to medication", 
    "shes having trouble with her oxygen levels", 
    "his surgical site is bleeding",
    "hes trying to jump out the window right now",
    "shes swallowing everything she can find including batteries",
    "hey nurse I think he just swallowed his tongue during the seizure",
    "doctor come quick shes turning purple and grabbing her throat",
    "someone help my father just collapsed in the hallway", 
    "nurse my mother is speaking gibberish and her face is drooping", 
    "look his arm is bent in a weird angle after the fall",
    "doctor the patient is spitting up blood and cant breathe",
    "hey security this patient has a knife and is threatening people", 
    "nurse come here his catheter is completely filled with blood",
    "doctor his trach tube came out and he cant breathe", 
    "hey the patient just jumped out of the window",
    "nurse my grandmother keeps saying shes seeing demons everywhere", 
    "doctor she just bit through her tongue during the seizure",
    "hey the patient is trying to pull out all his IV lines",
    "nurse my father is hallucinating and trying to fight everyone",
    "look at her stomach its getting bigger by the minute",
    "doctor the wound vac is making weird noises and smoking", 
    "nurse his skin is peeling off in sheets after taking that medicine", 
    "doctor the patient is having severe tremors and foaming at mouth", 
    "hey security theres an angry family member with a gun",
    "nurse the dialysis machine is beeping red and wont stop", 
    "look her legs are completely paralyzed after that injection", 
    "doctor he keeps screaming about bugs under his skin", 
    "hey the patient in room 4 is hanging from the doorknob", 
    "nurse my mother cant remember how to swallow anymore", 
    "look his chest tube is filling with bright red blood", 
    "doctor she keeps pulling out her hair and eating it", 
    "hey the patient just drank all the hand sanitizer", 
    "look her eyes are pointing in different directions now", 
    "hey she just had a bowel movement thats pure blood", 
    "doctor the patient is convulsing and bit off part of her tongue",
    "hey security this visitor is threatening to shoot everyone",
    "nurse come quick theres smoke coming from the oxygen tank"
        ]
    return sentences;