def getNonEmergencyArray():
    sentences = [
       "What are some good activities to keep her engaged during the day?",
        "How can I help him maintain a regular sleep schedule?",
        "What's the best way to communicate with someone who has dementia?",
        "Are there any dietary recommendations for dementia patients?",
        "How often should I schedule doctor's appointments?",
        "What are some strategies for managing wandering behavior?",
        "How can I make our home safer for someone with dementia?",
        "What are some signs that indicate the dementia is progressing?",
        "How can I help him maintain his independence as much as possible?",
        "What are some good ways to stimulate her memory?",
        "How can I manage my own stress as a caregiver?",
        "What kind of exercise is appropriate for someone with dementia?",
        "How can I help him maintain social connections?",
        "What are some tips for managing personal hygiene routines?",
        "How can I create a calm and soothing environment at home?",
        "What are some strategies for dealing with repetitive questions?",
        "How can I encourage her to eat regularly?",
        "What are some good ways to celebrate special occasions?",
        "How can I help him feel useful and needed?",
        "What are some signs of depression in dementia patients?",
        "How can I manage challenging behaviors without getting frustrated?",
        "What are some good books or resources about dementia care?",
        "How can I help her maintain her dignity throughout the progression of the disease?",
        "What are some tips for managing doctor's appointments effectively?",
        "How can I create a daily routine that works for both of us?",
        "What are some good ways to reminisce about the past?",
        "How can I encourage him to take his medications regularly?",
        "What are some strategies for managing sundowning symptoms?",
        "How can I help her feel comfortable with new caregivers?",
        "What are some good ways to incorporate music into daily care?",
        "How can I manage his finances responsibly?",
        "What are some tips for successful bathing routines?",
        "How can I help her feel safe when she's confused or disoriented?",
        "What are some good ways to celebrate small victories?",
        "How can I encourage him to stay physically active?",
        "What are some strategies for managing incontinence with dignity?",
        "How can I help her maintain her appearance and self-esteem?",
        "What are some good ways to involve family members in care?",
        "How can I create meaningful conversations when verbal skills are declining?",
        "What are some tips for managing doctor's appointments effectively?",
        "How can I help him feel comfortable in new environments?",
        "What are some strategies for managing agitation or restlessness?",
        "How can I encourage her to participate in household tasks?",
        "What are some good ways to incorporate pet therapy?",
        "How can I manage medication schedules effectively?",
        "What are some tips for creating a memory book?",
        "How can I help him maintain his cultural or religious practices?",
        "What are some strategies for managing hallucinations calmly?",
        "How can I encourage her to stay hydrated throughout the day?",
        "What are some good ways to celebrate holidays without overwhelming her?",
        "How can I help him feel comfortable with personal care routines?",
        "What are some strategies for managing anxiety in dementia patients?",
        "How can I create a safe outdoor space for her to enjoy?",
        "What are some good ways to incorporate aromatherapy into daily care?",
        "How can I manage his doctor's appointments and medical information effectively?",
        "What are some tips for creating a relaxing bedtime routine?",
        "How can I help her maintain connections with grandchildren?",
        "What are some strategies for managing paranoia or suspicion?",
        "How can I encourage him to express his feelings?",
        "What are some good ways to incorporate art therapy into daily activities?",
        "How can I manage household chores while providing care?",
        "What are some tips for creating a memory-friendly home environment?",
        "How can I help her feel secure when I need to leave the house?",
        "What are some strategies for managing anger or frustration in dementia patients?",
        "How can I encourage him to try new activities?",
        "What are some good ways to celebrate his life story?",
        "How can I manage my own health while caregiving?",
        "What are some tips for creating engaging sensory activities?",
        "How can I help her feel comfortable with changes in her appearance?",
        "What are some strategies for managing delusions compassionately?",
        "How can I encourage him to socialize with others?",
        "What are some good ways to incorporate nature into daily care?",
        "How can I manage financial and legal matters responsibly?",
        "What are some tips for creating a photo album together?",
        "How can I help her feel valued and appreciated?",
        "What are some strategies for managing sleep disturbances?",
        "How can I encourage him to express himself creatively?",
        "What are some good ways to celebrate small moments of joy?",
        "How can I manage my own emotional well-being as a caregiver?",
        "What are some tips for creating a comfortable dining environment?",
        "How can I help her maintain her sense of humor?",
        "What are some strategies for managing apathy or lack of interest?",
        "How can I encourage him to participate in gentle exercise?",
        "What are some good ways to incorporate touch and massage into daily care?",
        "How can I manage transportation needs safely?",
        "What are some tips for creating a memory wall or corner?",
        "How can I help her feel connected to her past accomplishments?",
        "What are some strategies for managing changes in taste or appetite?",
        "How can I encourage him to engage in brain-stimulating activities?",
        "What are some good ways to celebrate cultural traditions?",
        "How can I manage my own social life while caregiving?",
        "What are some tips for creating a safe bathroom environment?",
        "How can I help her feel comfortable with adaptive equipment?",
        "What are some strategies for managing changes in sexual behavior?",
        "How can I encourage him to maintain personal grooming habits?",
        "What are some good ways to incorporate music therapy into daily routines?",
        "How can I manage respite care effectively?",
        "What are some tips for creating a memory garden?",
        "How can I help her feel comfortable with changes in her abilities?",
        "What are some strategies for managing end-of-life care decisions compassionately?",
        "Can you show me how to properly transfer her from the bed to the wheelchair?",
        "I noticed she really enjoys listening to classical music during breakfast",
        "He seems more alert in the mornings after a good nights sleep",
        "Would you mind helping me organize his medication schedule?",
        "She hasnt eaten much today but shes drinking plenty of water",
        "The physical therapist suggested these new exercises for his mobility",
        "I think we should try serving smaller meals more frequently",
        "His mood seems to improve when we go for short walks in the garden",
        "The new medication schedule seems to be working better",
        "Could you demonstrate the proper way to help her with the walker?",
        "She really brightens up when we look through old family photos",
        "The occupational therapist left some helpful suggestions for daily activities",
        "His appetite has been better since we started playing soft music during meals",
        "Would you recommend any specific shoes for better balance?",
        "She seems to enjoy the morning routine weve established",
        "The memory games are really keeping him engaged",
        "I think we should adjust the room temperature its a bit warm in here",
        "Could you show me how to properly clean her dentures?",
        "He responds well to gentle back rubs before bedtime",
        "The art therapy sessions seem to calm her anxiety",
        "Should we consider getting a hospital bed for home use?",
        "She likes having her hair brushed it seems to relax her",
        "The new incontinence products are working much better",
        "Could you explain how to use this blood pressure monitor?",
        "He seems more comfortable with the new pillow arrangement",
        "The speech therapist suggested these communication exercises",
        "Would it be helpful to label the drawers and cabinets?",
        "She enjoys watching the birds at the new feeder outside her window",
        "The grab bars in the bathroom have made things much easier",
        "His balance is better when using the new walking shoes",
        "Could you recommend some easy stretching exercises?",
        "She prefers the vanilla nutritional supplements over chocolate",
        "The new schedule for visitors seems to work well",
        "Would you suggest any changes to his daily routine?",
        "Her coordination improves after the morning exercises",
        "The new bed positioning helps with his breathing",
        "Could you show me how to properly clean the feeding tube?",
        "She seems more comfortable with the elevated bed position",
        "The memory book we created helps with daily conversations",
        "His facial expressions show he enjoys the hand massages",
        "Would you recommend any specific activities for rainy days?",
        "She responds well to the aromatherapy diffuser",
        "The new medication organizer is very helpful",
        "Could you demonstrate proper lifting techniques?",
        "He seems more engaged during group activities",
        "The large print calendar helps her stay oriented",
        "Would it be beneficial to get a therapy ball?",
        "She enjoys the texture of these new blankets",
        "The morning sunshine seems to improve his mood",
        "Could you suggest some appropriate board games?",
        "Her appetite increases when we eat together",
        "The new shower chair makes bathing much safer",
        "Would you recommend any specific music for relaxation?",
        "He seems calmer when we maintain a consistent schedule",
        "The picture cards help with communication",
        "Could you show me how to properly position her in bed?",
        "She enjoys watching cooking shows on television",
        "The weighted blanket helps with nighttime restlessness",
        "Would these compression socks be helpful?",
        "He seems to prefer eating with the new adaptive utensils",
        "The large button remote control works well",
        "Could you suggest some simple craft projects?",
        "She likes having her feet massaged before bedtime",
        "The new night light helps prevent confusion",
        "Would it be good to get a reclining chair?",
        "He responds well to gentle background music",
        "The picture books spark good memories",
        "Could you recommend some easy word games?",
        "She enjoys watching the fish in the aquarium",
        "The new bed rail provides good support",
        "Would these slip resistant socks be useful?",
        "He seems more alert after morning coffee",
        "The therapeutic activities keep her engaged",
        "Could you suggest some breathing exercises?",
        "She likes the new soft toothbrush better",
        "The medication reminder app is very helpful",
        "Would you recommend any specific vitamins?",
        "He enjoys the weekly visits from the therapy dog",
        "The large print books are easier for her to read",
        "Could you show me how to use this pulse oximeter?",
        "She seems more relaxed during afternoon activities",
        "The new adaptive clothing is much easier to manage",
        "Would these grip handles help in the bathroom?",
        "He responds well to gentle voice commands",
        "The sensory activities keep her interested",
        "Could you suggest some balance exercises?",
        "She enjoys the texture of these stress balls",
        "The new bed wedge helps with positioning",
        "Would it be beneficial to get a therapy mat?",
        "He seems more comfortable with the room layout",
        "The picture schedule helps with daily tasks",
        "Could you recommend some memory exercises?",
        "She likes the new soft blanket texture",
        "The medication schedule chart is very clear",
        "Would these support stockings be helpful?",
        "He enjoys watching nature documentaries",
        "The reminiscence therapy seems effective",
        "Could you suggest some seated exercises?",
        "She responds well to gentle touch therapy",
        "The new bed padding is more comfortable",
        "Would these adaptive cups be useful?",
        "He seems calmer with the white noise machine",
        "The daily journal helps track his progress",
        "Could you show me proper grooming techniques?",
        "She enjoys the scent of lavender oil",
        "The new wheelchair cushion fits well",
        "Would these grip mats help prevent slipping?",
        "He likes the texture of these therapy putty exercises",
        "The large print playing cards work better",
        "Could you suggest some cognitive exercises?",
        "She seems more alert during morning activities",
        "The new bed alarm works effectively",
        "Would these support pillows be helpful?",
        "He responds well to music therapy sessions",
        "The picture menu helps with meal choices",
        "Could you recommend some range of motion exercises?",
        "She enjoys the weekly manicure sessions",
        "The new medication dispenser is working well",
        "Would these non slip mats be useful?",
        "He seems more engaged during art activities",
        "The daily exercise routine is showing progress",
        "Could you suggest some relaxation techniques?",
        "She likes the new soft washcloths",
        "The medication tracking app is helpful",
        "Would these support shoes be beneficial?",
        "He enjoys the weekly poetry readings",
        "The memory games keep him stimulated",
        "Could you show me transfer techniques?",
        "She responds well to gentle exercise",
        "The new bed sheets are more comfortable",
        "Would these adaptive utensils help?",
        "He seems calmer during morning routines",
        "The daily walks improve his mood",
        "Could you suggest some social activities?",
        "She enjoys the weekly baking sessions",
        "The new medication schedule works better",
        "Would these grip socks be helpful?",
        "He likes the texture of these therapy balls",
        "The large print newspaper is easier to read",
        "Could you recommend some hand exercises?",
        "She seems more relaxed during music time",
        "The new bed position helps with comfort",
        "Would these support handles be useful?",
        "He responds well to gentle stretching",
        "The picture books spark conversations",
        "Could you suggest some memory games?",
        "She enjoys the weekly art sessions",
        "The new medication timing is effective",
        "Would these non skid shoes help?",
        "He seems more alert during visits",
        "The daily routine chart works well",
        "Could you show me positioning techniques?",
        "She likes the new soft towels",
        "The medication reminder system helps",
        "Would these support gloves be beneficial?",
        "He enjoys the weekly music sessions",
        "The cognitive exercises show progress",
        "Could you suggest some breathing techniques?",
        "She responds well to gentle massage",
        "The new bed setup is working well",
        "Would these adaptive tools be helpful?",
        "He seems calmer during afternoon activities",
        "The daily exercises are showing improvement",
        "Could you recommend some balance activities?",
        "She enjoys the weekly gardening sessions",
        "The new medication system is effective",
        "Would these grip aids be useful?",
        "He likes the texture of these therapy tools",
        "The large print puzzle books work better",
        "Could you suggest some stretching exercises?",
        "She seems more engaged during craft time",
        "The new bed routine helps with sleep",
        "Would these support braces be helpful?",
        "He responds well to gentle movement",
        "The picture cards aid communication",
        "Could you show me exercise techniques?",
        "She enjoys the weekly social groups",
        "The new medication chart is clear",
        "Would these adaptive devices help?",
        "He seems more relaxed during reading time",
        "The daily schedule keeps him oriented",
        "Could you suggest some therapy activities?",
        "She likes the new soft blankets",
        "The medication organizer works well",
        "Would these support bands be useful?",
        "He enjoys the weekly exercise class",
        "The memory activities show progress",
        "Could you recommend some daily exercises?",
        "She responds well to gentle activities",
        "The new bed schedule helps routine",
        "Would these grip tools be helpful?",
        "He seems calmer during quiet time",
        "The daily activities keep him engaged",
        "Could you suggest some therapy games?",
        "She enjoys the weekly dance sessions",
        "The new medication routine works well",
        "Would these support wraps be beneficial?",
        "He likes the texture of these therapy mats",
        "The large print books are helpful",
        "Could you show me massage techniques?",
        "She seems more alert during activities",
        "The new bed setup helps positioning",
        "Would these adaptive aids be useful?",
        "He responds well to gentle exercise",
        "The picture books help with memory",
        "Could you suggest some daily activities?",
        "She enjoys the weekly craft sessions",
        "The new medication system works well",
        "I feel so overwhelmed with all the caregiving responsibilities sometimes",
        "Do you think she remembers who I am?",
        "Its breaking my heart to see him struggle with simple tasks",
        "The way his face lights up when he hears his favorite song is beautiful",
        "Im worried about burning out",
        "Sometimes I just need someone to talk to about all this",
        "Hand me that blue sweater please she gets cold easily",
        "Its hard watching my strong father become so dependent",
        "I miss our long conversations",
        "Could you help me set up the video call with his grandchildren?",
        "The grief comes in waves even though hes still here",
        "Remember to put his glasses on the right side table",
        "Im learning to treasure the small moments of clarity",
        "Sometimes I feel guilty for feeling frustrated",
        "The photo album always makes her smile",
        "I never thought Id have to parent my own parent",
        "Can you show me again how to work this lift?",
        "Its the little moments of recognition that keep me going",
        "Would you mind sitting with her while I take a short break?",
        "I feel lost when he doesnt recognize me",
        "The morning routine takes longer now but thats okay",
        "Sometimes I catch glimpses of who she used to be",
        "Im trying to be patient but some days are harder than others",
        "Just watching him sleep peacefully brings me comfort",
        "We need more adult diapers from the supply room",
        "Every smile feels like a gift now",
        "The hardest part is seeing her confused and scared",
        "I miss how things used to be between us",
        "Could you help me organize these family photos for her memory book?",
        "Sometimes I feel so alone in this journey",
        "The way he still tries to protect me breaks my heart",
        "Remember she likes her tea with just a little honey",
        "Im learning to live in his world now",
        "These moments of clarity are so precious",
        "Would you mind helping me move this chair closer to the window?",
        "I feel guilty for wanting some time to myself",
        "Its hard to keep explaining the same things over and over",
        "The love is still there even when the memories arent",
        "Sometimes I wonder if Im doing enough",
        "Can you help me understand these new medication instructions?",
        "I treasure every I love you even when its said to someone else",
        "The nights are the hardest when she gets confused",
        "Im trying to stay strong but sometimes I just need to cry",
        "Would you mind showing me how to use this new bed control?",
        "Its difficult watching them lose their independence",
        "I miss our Sunday family dinners the way they used to be",
        "Sometimes just holding his hand says everything",
        "The walker needs new tennis balls on the bottom",
        "I feel blessed to be able to care for her",
        "Its hard to remember who I am outside of being a caregiver",
        "Could you help me set up the room for physical therapy?",
        "I never knew love could be this patient",
        "The way she still remembers old songs amazes me",
        "Sometimes I feel like Im disappearing into this role",
        "Would you mind helping me organize his closet?",
        "I miss our morning coffee chats",
        "The small victories mean so much now",
        "Its strange how grief and joy can exist together",
        "Remember to keep the blinds open during the day",
        "I wish I could make it all better",
        "The quiet moments are sometimes the hardest",
        "Could you show me how to work this oxygen machine?",
        "Im learning to find joy in different ways now",
        "Sometimes I forget to take care of myself",
        "The way he still tries to make me laugh touches my heart",
        "Would you mind helping me with the shower routine?",
        "I never knew I could be this strong",
        "Its hard watching them struggle with basic tasks",
        "The family photos seem to bring her peace",
        "Sometimes I feel like Im losing myself in this",
        "Could you help me understand these therapy exercises?",
        "I miss our long walks together",
        "The way she still says thank you means everything",
        "Remember to keep her favorite blanket close",
        "Im trying to create new memories while we still can",
        "The calendar needs to be updated for next month",
        "Sometimes I feel guilty for feeling tired",
        "Would you mind helping me with the feeding schedule?",
        "I treasure every moment of recognition",
        "Its hard to watch them lose their words",
        "The simple moments mean the most now",
        "Could you show me how to use this new bed pad?",
        "I miss our evening talks",
        "The way he still tries to help others touches me",
        "Sometimes I wonder what theyre thinking",
        "Remember to keep the room temperature steady",
        "I feel blessed and heartbroken at the same time",
        "The morning light seems to calm her",
        "Would you mind helping me with these compression socks?",
        "I never knew love could hurt this much",
        "Its strange how time moves differently now",
        "The photo albums need to be reorganized",
        "Sometimes I feel like Im living in two worlds",
        "Could you help me understand these new exercises?",
        "I miss our shopping trips together",
        "The way she still remembers my name is precious",
        "Remember to keep the night light on",
        "Im learning to find peace in the quiet moments",
        "The medication schedule needs to be updated",
        "Sometimes I feel guilty for wanting a break",
        "Would you mind helping me with the bedtime routine?",
        "I treasure every smile now",
        "Its hard watching them struggle with memories",
        "The simple tasks take so much longer now",
        "Could you show me how to use this new chair lift?",
        "I miss our garden talks",
        "The way he still tries to dance makes me smile",
        "Sometimes I feel like time is slipping away",
        "Remember to keep her favorite music playing",
        "I feel grateful for the good days",
        "The evening routine is getting easier",
        "Would you mind helping me with these therapy balls?",
        "I never knew I could love this deeply",
        "Its strange how roles have reversed",
        "The supply cabinet needs restocking",
        "Sometimes I feel like Im not doing enough",
        "Could you help me understand these new protocols?",
        "I miss our cooking sessions together",
        "The way she still prays touches my heart",
        "Remember to keep his glasses clean",
        "Im learning to live in the present moment",
        "The weekly schedule needs updating",
        "Sometimes I feel overwhelmed by the responsibility",
        "Would you mind helping me with these exercises?",
        "I treasure every moment of connection",
        "Its hard watching them lose their skills",
        "The simple pleasures mean more now",
        "Could you show me how to use this new device?",
        "I miss our daily routines",
        "The way he still tries to help is touching",
        "Sometimes I feel like Im losing my patience",
        "Remember to keep the room organized",
        "I feel blessed to have this time together",
        "The morning routine is getting smoother",
        "Would you mind helping me with these stretches?",
        "I never knew caregiving could be so complex",
        "Its strange how love grows stronger through this",
        "The activity calendar needs updating",
        "Sometimes I feel like Im on an emotional roller coaster",
        "Could you help me understand these new techniques?",
        "I miss our holiday traditions",
        "The way she still shows concern for others amazes me",
        "Remember to keep his favorite snacks stocked",
        "Im learning to appreciate the small moments",
        "The daily log needs to be filled out",
        "Sometimes I feel guilty for feeling sad",
        "Would you mind helping me with these memory games?",
        "I treasure every peaceful moment",
        "Its hard watching them struggle with daily tasks",
        "The simple conversations mean everything now",
        "Could you show me how to use this new equipment?",
        "I miss our morning rituals",
        "The way he still remembers old stories is precious",
        "Sometimes I feel like Im learning a new language",
        "Remember to keep her routine consistent",
        "I feel grateful for the support system",
        "The evening activities need planning",
        "Would you mind helping me with these comfort measures?",
        "I never knew love could be this patient",
        "Its strange how time both drags and flies",
        "The supply list needs updating",
        "Sometimes I feel like Im living in slow motion",
        "Could you help me understand these new procedures?",
        "I miss our shared laughter",
        "The way she still tries to help others is beautiful",
        "Remember to keep his dignity intact",
        "Im learning to find strength in vulnerability",
        "The weekly activities need organizing",
        "Sometimes I feel like Im walking on eggshells",
        "Would you mind helping me with these daily tasks?",
        "I treasure every moment of peace",
        "Its hard watching them navigate this journey",
        "The simple touches mean so much now",
        "Could you show me how to use this new tool?",
        "I miss our quiet moments",
        "The way he still shows affection touches me",
        "Sometimes I feel like Im their anchor",
        "Remember to keep her world peaceful",
        "I feel blessed by these challenging moments",
        "The daily schedule needs adjusting",
        "Would you mind helping me with these care routines?",
        "I never knew I could be this adaptable",
        "Its strange how love transcends memory",
        "The care plan needs reviewing",
        "Sometimes I feel like Im their protector",
        "Could you help me understand these new methods?",
        "The way she held my hand today made everything worth it",
        "Im scared of what tomorrow might bring but trying to stay present",
        "Could you grab an extra set of sheets from the supply closet?",
        "Sometimes when he smiles I see glimpses of his younger self",
        "Its amazing how much strength you can find when you need it",
        "The doctor mentioned adjusting his evening medication schedule"
        ]
    return sentences;